version: '3'

services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile                 
    container_name: myapp
    ports:
      - 8080:80
    extra_hosts:
        - host.docker.internal:172.17.0.1
    volumes:
        - '.:/var/www/html'
